//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepairWilliam121
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Description { get; set; }
        public int EquipmentID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int RepairTypeID { get; set; }
        public int StatusID { get; set; }
        public int PriorityID { get; set; }
        public int ClientID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<int> DaysSpent { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual RepairType RepairType { get; set; }
        public virtual User User { get; set; }
        public virtual RequestPriority RequestPriority { get; set; }
        public virtual Status Status { get; set; }
    }
}
